version: '3.1'
services:
  front:
    container_name: web-postgresql
      build: ./front-end/
      ports:
        - "8081:8081"
      depends_on:
        - back

  back:
    container_name: springboot-postgresql
    build: ./back-end/
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/FlightAndRoute"
    depends_on:
      - postgresqldb

  postgresqldb:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: FlightAndRoute
    ports:
      - "5432:5432"
    restart: always