version: '3.1'
services:

  app:
    container_name: springboot-postgresql
    build: ./
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/FlightAndRoute"
    ports:
      - "8081:8081"
    depends_on:
      - postgresqldb

  postgresqldb:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: FlightAndRoute
    ports:
      - "5432:5432"
    restart: always